export const BunriPosts = [
  {
    id: 1,
    title: "첫 번째로 분리한 글",
    content: "감자깡",
    author: "작성자3",
    views: 120,
    date: "2024-03-13",
    likes: 6,
  },
  {
    id: 2,
    title: "두 번째로 분리한 글",
    content: "고구마깡",
    author: "작성자5",
    views: 5,
    date: "2024-03-14",
    likes: 7,
  },
  {
    id: 3,
    title: "세 번째로 분리한 글",
    content: "감자깡",
    author: "작성자3",
    views: 10,
    date: "2024-03-13",
    likes: 5,
  },
  {
    id: 4,
    title: "네 번째로 분리한 글",
    content: "고구마깡",
    author: "작성자5",
    views: 5,
    date: "2024-03-14",
    likes: 7,
  },
  {
    id: 5,
    title: "다섯 번째로 분리한 글",
    content: "감자깡",
    author: "작성자3",
    views: 10,
    date: "2024-03-13",
    likes: 5,
  },
  {
    id: 6,
    title: "여섯 번째로 분리한 글",
    content: "양파깡",
    author: "작성자5",
    views: 2424,
    date: "2024-03-28",
    likes: 345,
  },
  {
    id: 7,
    title: "일곱 번째로 분리한 글",
    content: "감자깡",
    author: "작성자3",
    views: 10,
    date: "2024-03-13",
    likes: 5,
  },
  {
    id: 8,
    title: "여덟 번째로 분리한 글",
    content: "고구마깡",
    author: "작성자5",
    views: 5,
    date: "2024-03-14",
    likes: 7,
  },
  {
    id: 9,
    title: "아홉 번째로 분리한 글",
    content: "감자깡",
    author: "작성자3",
    views: 10,
    date: "2024-03-13",
    likes: 5,
  },
  {
    id: 10,
    title: "열 번째로 분리한 글",
    content: "고구마깡",
    author: "작성자5",
    views: 5,
    date: "2024-03-14",
    likes: 7,
  },
  {
    id: 11,
    title: "열한 번째로 분리한 글",
    content: "감자깡",
    author: "작성자11",
    views: 10,
    date: "2024-03-13",
    likes: 5,
  },
  {
    id: 12,
    title: "열두 번째로 분리한 글",
    content: "고구마깡",
    author: "작성자12",
    views: 5,
    date: "2024-03-14",
    likes: 7,
  },
  {
    id: 112,
    title: "분리분리분리분리분리분리분리분리분리분리분리분리",
    content: "분리수거",
    author: "분리왕",
    views: 777,
    date: "2024-03-24",
    likes: 777,
  },
];
